FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  PKG="apache24"
  pkg install -y FreeBSD-utilities "${PKG}"

  mkdir -p /tmp/root/etc /tmp/root/libexec /tmp/root/var/run /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run

  for bin in $(pkg info -l "${PKG}" | grep "bin/"); do
    mkdir -p "/tmp/root$(dirname "${bin}")"
    cp "${bin}" "/tmp/root$(dirname "${bin}")"
    for lib in $(ldd -f '%p\n' -f '' "${bin}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/usr/local/libexec/apache24
  for mod in /usr/local/libexec/apache24/*; do
    cp "${mod}" /tmp/root/usr/local/libexec/apache24/
    for lib in $(ldd -f '%p\n' -f '' "${mod}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/usr/local/etc /tmp/root/usr/local/www /tmp/root/var/log
  cp -r /usr/local/etc/apache24 /tmp/root/usr/local/etc/
  rm /tmp/root/usr/local/etc/apache24/*.sample /tmp/root/usr/local/etc/apache24/extra/*.sample
  cp -r /usr/local/www/apache24 /tmp/root/usr/local/www/
  ln -s /dev/stdout /tmp/root/var/log/httpd-access.log
  ln -s /dev/stderr /tmp/root/var/log/httpd-error.log
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

EXPOSE 80
CMD ["httpd", "-DFOREGROUND"]
