FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  pkg install -y kubectl FreeBSD-utilities

  mkdir -p /tmp/root/etc /tmp/root/bin /tmp/root/libexec /tmp/root/var/run /tmp/root/usr/bin /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp $(which kubectl) /tmp/root/bin
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run
  for lib in $(ldd -f '%p\n' -f '' /tmp/root/bin/kubectl); do
      mkdir -p "/tmp/root$(dirname "${lib}")"
      cp "${lib}" "/tmp/root$(dirname "${lib}")"
  done
  mkdir -p /tmp/root/.kube
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

ENV KUBECONFIG /.kube/config
ENTRYPOINT ["/bin/kubectl"]
CMD ["--help"]
