FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  PKG="busybox"
  pkg install -y FreeBSD-utilities "${PKG}"

  mkdir -p /tmp/root/etc /tmp/root/libexec /tmp/root/var/run /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run

  for bin in $(pkg info -l "${PKG}" | grep "bin/"); do
    mkdir -p "/tmp/root$(dirname "${bin}")"
    cp "${bin}" "/tmp/root$(dirname "${bin}")"
    for lib in $(ldd -f '%p\n' -f '' "${bin}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/bin /tmp/root/usr/bin
  for applet in $(busybox --list); do
      ln -s "$(which busybox)" "/tmp/root/bin/${applet}"
  done
  ln -s ../../bin/env /tmp/root/usr/bin/env
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

CMD ["sh"]
