FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  pkg install -y fluent-bit FreeBSD-utilities

  mkdir -p /tmp/root/etc /tmp/root/bin /tmp/root/libexec /tmp/root/var/run /tmp/root/usr/bin /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp $(which fluent-bit) /tmp/root/bin
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run
  for lib in $(ldd -f '%p\n' -f '' /tmp/root/bin/fluent-bit); do
      mkdir -p "/tmp/root$(dirname "${lib}")"
      cp "${lib}" "/tmp/root$(dirname "${lib}")"
  done
  mkdir -p /tmp/root/etc/fluent-bit
  cp -r /usr/local/etc/fluent-bit/*.conf /tmp/root/etc/fluent-bit
  /tmp/root/bin/fluent-bit -J > /tmp/root/etc/fluent-bit/schema.json
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

EXPOSE 2020
CMD ["/bin/fluent-bit", "-c", "/etc/fluent-bit/fluent-bit.conf"]
