FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  PKG="redis"
  pkg install -y FreeBSD-utilities "${PKG}"

  mkdir -p /tmp/root/etc /tmp/root/libexec /tmp/root/var/run /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run

  for bin in $(pkg info -l "${PKG}" | grep "bin/"); do
    mkdir -p "/tmp/root$(dirname "${bin}")"
    cp "${bin}" "/tmp/root$(dirname "${bin}")"
    for lib in $(ldd -f '%p\n' -f '' "${bin}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/usr/local/etc /tmp/root/var/log/redis /tmp/root/data /tmp/root/tmp
  sed '
    s/^bind/#bind/
    s/^protected-mode.*/protected-mode no/
    s/^daemonize.*/daemonize no/
    s/^pidfile/#pidfile/
    s|^dir.*|dir /data|
    /^\ *#/d
    /^\ *$/d
    ' /usr/local/etc/redis.conf.sample > /tmp/root/usr/local/etc/redis.conf
  sed '
    s/^protected-mode.*/protected-mode no/
    s/^daemonize.*/daemonize no/
    s/^pidfile/#pidfile/
    s|^dir.*|dir /tmp|
    /^\ *#/d
    /^\ *$/d
  ' /usr/local/etc/sentinel.conf.sample > /tmp/root/usr/local/etc/sentinel.conf
  ln -s /dev/stdout /tmp/root/var/log/redis/redis.log
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

VOLUME /data
WORKDIR /data

EXPOSE 6379
CMD ["redis-server", "/usr/local/etc/redis.conf"]
