FROM ghcr.io/freebsd/freebsd-runtime:14.3 AS builder

RUN <<EOF
  umask 0022
  PKG="nginx"
  pkg install -y FreeBSD-utilities "${PKG}"

  mkdir -p /tmp/root/etc /tmp/root/libexec /tmp/root/var/run /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run

  for bin in $(pkg info -l "${PKG}" | grep "bin/"); do
    mkdir -p "/tmp/root$(dirname "${bin}")"
    cp "${bin}" "/tmp/root$(dirname "${bin}")"
    for lib in $(ldd -f '%p\n' -f '' "${bin}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/usr/local/libexec/nginx
  for mod in /usr/local/libexec/nginx/*; do
    cp "${mod}" /tmp/root/usr/local/libexec/nginx/
    for lib in $(ldd -f '%p\n' -f '' "${mod}"); do
        mkdir -p "/tmp/root$(dirname "${lib}")"
        cp "${lib}" "/tmp/root$(dirname "${lib}")"
    done
  done

  mkdir -p /tmp/root/usr/local/etc /tmp/root/usr/local/www/nginx /tmp/root/var/log/nginx /tmp/root/var/tmp/nginx
  cp -r /usr/local/etc/nginx /tmp/root/usr/local/etc/nginx
  rm /tmp/root/usr/local/etc/nginx/*-dist
  cp -r /usr/local/www/nginx-dist /tmp/root/usr/local/www/nginx-dist
  cp /usr/local/www/nginx/index.html /tmp/root/usr/local/www/nginx/index.html
  ln -s /dev/stdout /tmp/root/var/log/nginx/access.log
  ln -s /dev/stderr /tmp/root/var/log/nginx/error.log
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
