FROM ghcr.io/fst777/runtime-pkg AS builder

RUN <<EOF
  umask 0022
  pkg install -y nginx FreeBSD-utilities

  mkdir -p /tmp/root/etc /tmp/root/bin /tmp/root/libexec /tmp/root/var/run /tmp/root/usr/bin /tmp/root/root
  cp /etc/passwd /etc/master.passwd /etc/pwd.db /etc/spwd.db /etc/group /tmp/root/etc
  cp $(which nginx) /tmp/root/bin
  cp /libexec/ld-elf.* /tmp/root/libexec
  cp /var/run/ld-elf.so.hints /tmp/root/var/run
  for lib in $(ldd -f '%p\n' -f '' /tmp/root/bin/nginx); do
      mkdir -p "/tmp/root$(dirname "${lib}")"
      cp "${lib}" "/tmp/root$(dirname "${lib}")"
  done

  mkdir -p /tmp/root/usr/local/etc /tmp/root/usr/local/www/nginx /tmp/root/var/log/nginx /tmp/root/var/tmp/nginx
  cp -r /usr/local/etc/nginx /tmp/root/usr/local/etc/nginx
  rm /tmp/root/usr/local/etc/nginx/*-dist
  cp -r /usr/local/www/nginx-dist /tmp/root/usr/local/www/nginx-dist
  cp /usr/local/www/nginx/index.html /tmp/root/usr/local/www/nginx/index.html
  ln -s /dev/stdout /tmp/root/var/log/nginx/access.log
  ln -s /dev/stderr /tmp/root/var/log/nginx/error.log
EOF


FROM scratch
LABEL maintainer="Frans-Jan van Steenbeek <frans-jan@van-steenbeek.net>"

COPY --from=builder /tmp/root/ /

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
