name: Publish container images

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["**/LICENSE", "**.md", ".github/**", "build-assets/**"]
  schedule:
    - cron: "37 10 * * 6"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64]

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Build
        uses: cross-platform-actions/action@v1.2.0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 15.0
          environment_variables: HOSTNM
          run: |
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            echo " > Set-up the build VM"
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            sudo ./build-assets/setup.sh
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            echo " > Build containers"
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            sudo ./build-assets/build.sh "${{ matrix.architecture }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.architecture }}
          retention-days: 1
          path: |
            ./*.${{ matrix.architecture }}.tar
            ./*.${{ matrix.architecture }}.tags
            ./*.${{ matrix.architecture }}.yml
