name: Publish container images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@v0.28.0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 14.2
          environment_variables: HOSTNM
          run: |
            sudo ./build-assets/setup.sh
            LIST=""
            for c in Containerfiles/*; do
              for d in $(grep FROM "${c}" | cut -d ' ' -f 2); do
                if [ -r "Containerfiles/${d}" ]; then
                  LIST="${LIST}$(basename "${c}") ${d}\n"
                fi
              done
            done
            for c in $(echo -e "${LIST}" | tsort | tail -r); do
              sudo buildah bud -t "${c}:latest" "./Containerfiles/${c}"
              sudo buildah push "${c}:latest" "oci-archive:${c}.${{ matrix.architecture}}.tar:${c}:latest"
            done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./*.${{ matrix.architecture }}.tar
          retention-days: 1

  list:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - id: containers
        run: |
          echo "::set-output name=containers::$(cd Containerfiles; ls * | jq -R -s -c 'split("\n")[:-1]')"

  upload:
    runs-on: ubuntu-24.04
    needs: [build, list]
    strategy:
      matrix:
        container: ${{ fromJson(needs.list.outputs.containers) }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create manifest
        run: |
          buildah manifest create ${{ matrix.container }}:latest oci-archive:${{ matrix.container }}.x86-64.tar oci-archive:${{ matrix.container }}.arm64.tar

      - name: Registry owner to lowercase
        env:
          GHOWNER: '${{ github.repository_owner }}'
        run: |
          echo "GHOWNER_LC=${GHOWNER,,}" >> ${GITHUB_ENV}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ matrix.container }}
          tags: latest
          registry: ghcr.io/${{ env.GHOWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
