name: Publish container images

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["**/LICENSE", "**.md", ".github/**", "build-assets/**"]
  schedule:
    - cron: "37 10 * * 6"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@9a4355714f90c057476048788b82147e99b7c0f0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 14.3
          environment_variables: HOSTNM
          run: |
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            echo " > Set-up the build VM"
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            sudo ./build-assets/setup.sh
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            echo " > Build containers"
            echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            sudo ./build-assets/build.sh "${{ matrix.architecture }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.architecture }}
          retention-days: 1
          path: |
            ./*.${{ matrix.architecture }}.tar
            ./*.${{ matrix.architecture }}.tags
            ./*.${{ matrix.architecture }}.yml

  list:
    runs-on: ubuntu-24.04

    outputs:
      containers: ${{ steps.containers.outputs.containers }}

    steps:
      - uses: actions/checkout@v4

      - name: List containers
        id: containers
        run: |
          echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo " > List containers for the matrix"
          echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          cd containers
          echo "containers=$(ls -d * | jq -R -s -c 'split("\n")[:-1]')" >> "${GITHUB_OUTPUT}"

  push:
    runs-on: ubuntu-24.04
    needs: [build, list]
    strategy:
      matrix:
        container: ${{ fromJson(needs.list.outputs.containers) }}

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create manifest
        id: manifest
        run: |
          echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          echo " > Package manifest"
          echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
          ./build-assets/package.sh "${{ matrix.container }}"

      - name: Registry owner to lowercase
        env:
          GHOWNER: '${{ github.repository_owner }}'
        run: |
          echo "GHOWNER_LC=${GHOWNER,,}" >> "${GITHUB_ENV}"

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ matrix.container }}
          tags: ${{ steps.manifest.outputs.tags }}
          registry: ghcr.io/${{ env.GHOWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
