name: Publish container images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Registry
        run: |
          podman run -dp 5000:5000 --name registry registry
          echo "HOSTNM=$(hostname)" >> ${GITHUB_ENV}

      - name: Build
        uses: cross-platform-actions/action@v0.28.0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 14.2
          environment_variables: HOSTNM
          run: |
            sudo ./build-assets/setup.sh
            sudo buildah bud -t runtime-pkg:${{ matrix.architecture }} ./Containerfiles/runtime-pkg
            sudo buildah push --tls-verify=false runtime-pkg:${{ matrix.architecture }} ${HOSTNM}:5000/runtime-pkg:${{ matrix.architecture }}

      - name: Export image
        run: |
          podman pull --tls-verify=false localhost:5000/runtime-pkg:${{ matrix.architecture }}
          podman push runtime-pkg:${{ matrix.architecture }} oci-archive:runtime-pkg.${{ matrix.architecture}}.tar:runtime-pkg:${{ matrix.architecture }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runtime-pkg.${{ matrix.architecture }}
          path: runtime-pkg.${{ matrix.architecture }}.tar

  upload:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create manifest
        run: |
          buildah pull oci-archive:runtime-pkg.x86-64.tar
          buildah pull oci-archive:runtime-pkg.arm64.tar
          buildah manifest create runtime-pkg:latest
          buildah manifest add runtime-pkg:latest runtime-pkg:x86-64
          buildah manifest add runtime-pkg:latest runtime-pkg:arm64

      - name: Registry owner to lowercase
        env:
          GHOWNER: '${{ github.repository_owner }}'
        run: |
          echo "GHOWNER_LC=${GHOWNER,,}" >> ${GITHUB_ENV}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: runtime-pkg
          tags: latest
          registry: ghcr.io/{{ env.GHOWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
