name: Testing GHA

on:
  workflow_dispatch:
  push:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64, arm64]

    steps:
      - name: Test
        uses: cross-platform-actions/action@v0.28.0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 14.2
          run: |
            uname -a
