name: Testing GHA

on:
  workflow_dispatch:
  push:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [x86-64, arm64]

    steps:
      - name: Test
        uses: cross-platform-actions/action@9a4355714f90c057476048788b82147e99b7c0f0
        with:
          operating_system: freebsd
          architecture: ${{ matrix.architecture }}
          version: 14.3
          run: |
            uname -a
